FROM debian:buster

RUN apt-get update && apt-get install -y \
        curl \
        git \
        wget \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libonig-dev \
        libxml2-dev \
        libzip-dev

RUN apt-get -y install lsb-release apt-transport-https ca-certificates
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list
RUN apt-get update && apt-get install -y \
 php7.3 \
 php7.3-fpm \
 php7.3-mysql \
 php7.3-pgsql \
 php-xdebug \
 php-intl

COPY ./fpm/pool.d/ /etc/php/7.3/fpm/pool.d
COPY ./fpm/conf.d/additional-php.ini /etc/php/7.3/fpm/conf.d/99-additional-php.ini
COPY ./cli/conf.d/additional-cli-php.ini /etc/php/7.3/cli/conf.d/99-additional-cli-php.ini

# Куда же без composer'а.
#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Добавим свой php.ini, можем в нем определять свои значения конфига
# ADD php.ini /usr/local/etc/php/conf.d/40-custom.ini

# Указываем рабочую директорию для PHP
WORKDIR /var/www

RUN /bin/bash service php7.3-fpm start

# Запускаем контейнер
# Из документации: The main purpose of a CMD is to provide defaults for an executing container. These defaults can include an executable, 
# or they can omit the executable, in which case you must specify an ENTRYPOINT instruction as well.
# CMD ["service", "php7.3-fpm", "restart", "&&", "/bin/bash"]
CMD /bin/bash service php7.3-fpm restart && /bin/bash

# EXPOSE 9000