# Версия docker-compose
version: '3.8'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:latest
        container_name: 'nginx'
        env_file:
            - .env
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ${PROJECTS_DIR}:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
        # restart: always
    php:
        build: 
            context: ./images/php
            dockerfile: Dockerfile
            args:
                PHP_VERSION: ${PHP_VERSION}
        container_name: 'php'
        env_file:
            - .env
        # будет добавлено в /etc/hosts
        extra_hosts:
            - "dc-dc-01:172.16.243.218"
            - "api.skl-co.lh:172.18.0.1"
        # монтируем директорию с проектами
        volumes:
            - ${PROJECTS_DIR}:/var/www
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        # restart: always
    # uncomment if you need rabbitmq
    # rabbitmq:
    #     image: rabbitmq:3-management
    #     container_name: 'rabbitmq'
    #     ports:
    #         - "15672:15672" # https://127.0.0.1:15672
    #         - "5672:5672"