version: '3.8'
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'rabbitmq'
        ports:
            - "15672:15672" # https://127.0.0.1:15672
            - "5672:5672"